workflows:
  openlineage-java:
    jobs:
      - build-client-java
      - integration-test-integration-spark:
          context: integration-tests
          matrix:
            parameters:
              spark-version: ['3.1.3']
      - workflow_complete:
          requires:
            - integration-test-integration-spark


